apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  annotations:
    field.knot8.io/foo: kptr:/spec/template/spec/containers/~{"name":"app"}]/env/~{"name":"FOO"}
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: app
        image: debian:10
        args:
        - bash
        - "-c"
        - |
          echo $FOO
          while true; do sleep 100000; done
        env:
          - name: FOO
            value: bar # 8< knot8.io/foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  annotations:
    field.knot8.io/foo: kptr:/foo
data:
  foo: bar # 8< field.knot8.io/foo
