apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  annotations:
    # knot8.vmware.com/foo: jsonpath:.spec.template.spec.containers[?(@.name=="app")].env[?(@.name=="foo")].value
    knot8.vmware.com/foo: kptr:/spec/template/spec/containers/~[name=app]/env/~[name=foo]
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: app
        image: debian:10
        args:
        - bash
        - "-c"
        - |
          echo $FOO
          while true; do sleep 100000; done
        env:
          - name: FOO
            value: bar # 8< knot8.vmware.com/foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  annotations:
    knot8.vmware.com/foo: kptr:/foo
data:
  foo: bar # 8< knot8.vmware.com/foo
